In [0]:
-- Selecting current catalog and schema
USE CATALOG test_drive;
USE SCHEMA road_crash;

-- Joining the crash, casualty and units tables
SELECT 
    c.REPORT_ID,
    c.longitude,
    c.latitude,
    c.`Stats Area`,
    c.Suburb,
    c.Postcode,
    c.`LGA Name`,
    c.`Total Units`,
    c.`Total Cas` as Total_Casualties,
    c.`Total Fats` as Total_Fatalities,
    c.`Road Surface`,
    c.`Moisture Cond`,
    c.`Weather Cond`,
    c.`DayNight`,
    c.Year,
    c.Month,
    c.Day,
    c.Time,
    c.`Area Speed`,
    u.`Unit No`,
    u.`Unit Type`,
    u.`Veh Year`,
    u.`Direction Of Travel`,
    u.Sex as Driver_Sex,
    u.Age as Driver_Age,
    cas.CASUALTY_NUMBER,
    cas.`Casualty Type`,
    cas.Sex as Casualty_Sex,
    cas.AGE as Casualty_Age,
    cas.`Position In Veh`,
    cas.`Thrown Out`,
    cas.`Injury Extent`,
    cas.`Seat Belt`,
    cas.Helmet,
    cas.Hospital
FROM test_drive.road_crash.crash c
LEFT JOIN test_drive.road_crash.units u ON c.REPORT_ID = u.REPORT_ID
LEFT JOIN test_drive.road_crash.casualty cas ON u.REPORT_ID = cas.REPORT_ID 
                                         AND u.`Unit No` = cas.UND_UNIT_NUMBER
ORDER BY c.REPORT_ID, u.`Unit No`, cas.CASUALTY_NUMBER;

-- Create a reusable view of the above Select statement
CREATE VIEW IF NOT EXISTS test_drive.road_crash.vw_crash_details AS
SELECT 
    c.REPORT_ID,
    c.longitude,
    c.latitude,
    c.`Stats Area`,
    c.Suburb,
    c.Postcode,
    c.`LGA Name`,
    c.`Total Units`,
    c.`Total Cas` as Total_Casualties,
    c.`Total Fats` as Total_Fatalities,
    c.`Road Surface`,
    c.`Moisture Cond`,
    c.`Weather Cond`,
    c.`DayNight`,
    c.Year,
    c.Month,
    c.Day,
    c.Time,
    c.`Area Speed`,
    u.`Unit No`,
    u.`Unit Type`,
    u.`Veh Year`,
    u.`Direction Of Travel`,
    u.Sex as Driver_Sex,
    u.Age as Driver_Age,
    cas.CASUALTY_NUMBER,
    cas.`Casualty Type`,
    cas.Sex as Casualty_Sex,
    cas.AGE as Casualty_Age,
    cas.`Position In Veh`,
    cas.`Thrown Out`,
    cas.`Injury Extent`,
    cas.`Seat Belt`,
    cas.Helmet,
    cas.Hospital
FROM test_drive.road_crash.crash c
LEFT JOIN test_drive.road_crash.units u ON c.REPORT_ID = u.REPORT_ID
LEFT JOIN test_drive.road_crash.casualty cas ON u.REPORT_ID = cas.REPORT_ID 
                                         AND u.`Unit No` = cas.UND_UNIT_NUMBER
ORDER BY c.REPORT_ID, u.`Unit No`, cas.CASUALTY_NUMBER;

-- Select all reocrds from the view
SELECT * FROM test_drive.road_crash.vw_crash_details;

-- Describe the view
DESCRIBE EXTENDED test_drive.road_crash.vw_crash_details;

-- Create a materialized view of the above Select statement with column mapping enabled
CREATE OR REFRESH MATERIALIZED VIEW test_drive.road_crash.mv_crash_details
TBLPROPERTIES ('delta.columnMapping.mode' = 'name')
AS
SELECT 
    c.REPORT_ID,
    c.longitude,
    c.latitude,
    c.`Stats Area`,
    c.Suburb,
    c.Postcode,
    c.`LGA Name`,
    c.`Total Units`,
    c.`Total Cas` as Total_Casualties,
    c.`Total Fats` as Total_Fatalities,
    c.`Road Surface`,
    c.`Moisture Cond`,
    c.`Weather Cond`,
    c.`DayNight`,
    c.Year,
    c.Month,
    c.Day,
    c.Time,
    c.`Area Speed`,
    u.`Unit No`,
    u.`Unit Type`,
    u.`Veh Year`,
    u.`Direction Of Travel`,
    u.Sex as Driver_Sex,
    u.Age as Driver_Age,
    cas.CASUALTY_NUMBER,
    cas.`Casualty Type`,
    cas.Sex as Casualty_Sex,
    cas.AGE as Casualty_Age,
    cas.`Position In Veh`,
    cas.`Thrown Out`,
    cas.`Injury Extent`,
    cas.`Seat Belt`,
    cas.Helmet,
    cas.Hospital
FROM test_drive.road_crash.crash c
LEFT JOIN test_drive.road_crash.units u ON c.REPORT_ID = u.REPORT_ID
LEFT JOIN test_drive.road_crash.casualty cas ON u.REPORT_ID = cas.REPORT_ID 
                                         AND u.`Unit No` = cas.UND_UNIT_NUMBER
ORDER BY c.REPORT_ID, u.`Unit No`, cas.CASUALTY_NUMBER;

-- Select all reocrds from the view
SELECT * FROM test_drive.road_crash.mv_crash_details;

-- Describe the materialized view
DESCRIBE EXTENDED test_drive.road_crash.mv_crash_details;